id: I07799039
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:12.052670
last_modified: 2023-01-04 11:30:12.052688
source_metadata:
  collections:
  - Butön Rinchen Drup Series
  - Works of Tibetan Masters
bases:
  '9679':
    title: Prayer to Butön Rinpoche
    base_file: 9679.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
